### ISSUE TITLE
Add dedicated load balancer API docs to DRC

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-dedicated-networking#16]
- [x] Update nexus-control configuration
- [ ] Update docs landing page (Complete update and merge before 1/9/2017 EGA.

**Comment by meker12** [comment]
Early access versions of the Dedicated load balancer docs are available at:  https://developer.rackspace.com/docs/dedicated-load-balancers/v2/

**Comment by cyrichardson** [comment]
Leave this issue open for now. Is not currently on developer.rackspace.com. Discussions under with Cesar Garza - @meker12 @klevenstein.

**Comment by catlook** [comment]
Update, @cyrichardson ?

**Comment by cyrichardson** [comment]
@catlook I'm going to close for now because of its age. Others can reopen if they want to do so.
