### ISSUE TITLE
Restore Travis build job

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-dedicated-networking#2]
@smashwilson   I had to restore this repo after accidentally deleting it instead of my fork. 

I tried to reactivate the build, by adding credentials to the Webhooks & Services Travis CI setup, but I don't seem to have the right token to run a build on the rackerlabs org.

Can you update the settings to re-activate the build?   See https://github.com/rackerlabs/docs-dedicated-networking/settings/hooks/7119373

Thank you!

**Comment by smashwilson** [comment]
Ah, you might have to have admin to that. For future reference, I enable Travis builds through the [Travis UI](https://travis-ci.org/profile/rackerlabs); it sets up the hook for you and everything when you flip the switch next to a repository. (Another option is `travis enable` with the Travis gem, but that takes some setup.)

**Comment by smashwilson** [comment]
As a sidenote I might need to re-issue the keys... Travis handles secrets by assymetric encryption with a keypair that it generates for each repository. If you deleted and recreated this repo, I'm not sure if it'll generate a new keypair or not. Let's see if a build completes on master or not.

**Comment by smashwilson** [comment]
Yeah, [I need to rekey](https://travis-ci.org/rackerlabs/docs-dedicated-networking/builds/105756486). Hand on.

**Comment by meker12** [comment]
OK. I wondered if there had to be a synchronization between the keys and the token.

**Comment by smashwilson** [comment]
Fixed with #3 and verified on master. :+1:
